//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receipt", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    public partial class Receipt : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ArticlesField;
        
        private decimal DiscountField;
        
        private System.Guid IdField;
        
        private string NumberField;
        
        private decimal SummField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Articles
        {
            get
            {
                return this.ArticlesField;
            }
            set
            {
                this.ArticlesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Summ
        {
            get
            {
                return this.SummField;
            }
            set
            {
                this.SummField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PutReceipt", ReplyAction="http://tempuri.org/IService/PutReceiptResponse")]
    void PutReceipt(WCFService.Receipt receipt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PutReceipt", ReplyAction="http://tempuri.org/IService/PutReceiptResponse")]
    System.Threading.Tasks.Task PutReceiptAsync(WCFService.Receipt receipt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetReceipts", ReplyAction="http://tempuri.org/IService/GetReceiptsResponse")]
    WCFService.Receipt[] GetReceipts(int number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetReceipts", ReplyAction="http://tempuri.org/IService/GetReceiptsResponse")]
    System.Threading.Tasks.Task<WCFService.Receipt[]> GetReceiptsAsync(int number);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void PutReceipt(WCFService.Receipt receipt)
    {
        base.Channel.PutReceipt(receipt);
    }
    
    public System.Threading.Tasks.Task PutReceiptAsync(WCFService.Receipt receipt)
    {
        return base.Channel.PutReceiptAsync(receipt);
    }
    
    public WCFService.Receipt[] GetReceipts(int number)
    {
        return base.Channel.GetReceipts(number);
    }
    
    public System.Threading.Tasks.Task<WCFService.Receipt[]> GetReceiptsAsync(int number)
    {
        return base.Channel.GetReceiptsAsync(number);
    }
}
